# .gitleaks.toml
[extend]
use_default = true

[[rules]]
description = "Generic Python API Key"
id = "generic-api-key"
regex = '''(?i)(?:key|api|token|secret|client|passwd|password|auth|access)(?:[0-9a-z\-_\t .:]{0,25})(?:[\s|']|[\s|"]){0,3}(?:=|>|:=|\|\|:|<=|=>|:)(?:'|\"|\s|=|\x60){0,5}([0-9a-z_\-=+/*.!?#$%&@^`~\\<>,;:]{10,150})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
secretGroup = 1
entropy = 3.5
keywords = [
    "key","api","token","secret","client","passwd","password","auth","access",
]

[allowlist]
paths = [
  '''.secrets_baseline\.json'''
]