default_language_version:
  python: python3.9
default_stages: [commit, push]
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8 .
        language: system
        types: [python]
      - entry: gitleaks protect --verbose --staged --no-banner
        id: gitleaks
        language: system
        name: gitleaks
        types: [file]
      # - id: isort
      #   name: isort
      #   entry: poetry run isort .
      #   language: system
      #   types: [python]
      # - id: poetry-check
      #   name: poetry check
      #   entry: poetry check
      #   language: system
      #   types: [python]
      # - id: ruff
      #   name: ruff
      #   entry: poetry run ruff --fix --no-cache --force-exclude .
      #   language: system
      #   types: [python]
      #   - id: detect_secrets
      #     name: detect_secrets
      #     entry: poetry run detect-secrets scan --baseline .secrets.baseline .
      #     language: system
      #     types: [python]
      #     exclude: package.lock.json
      # - id: detect-secrets
      #   name: detect-secrets
      #   # entry: git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
      #   entry: git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
      #   language: system
      #   types: [bash]
