services:
  qdrant:
    image: qdrant/qdrant:v1.13.4
    container_name: sci_papers_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:

networks:
  local:
    driver: bridge
