name: "mnist-classifier"
platform: "pytorch_backend"
max_batch_size: 32
version_policy: { all { }}
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [28, 28]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [10]
    label_filename: "labels.txt"
  }
]
instance_group [
  {
    kind: KIND_AUTO
    count: 1
  }
]